### ISSUE TITLE
Github-Gem unusable

### ISSUE THREAD

**Issue by aperrot42** [defunkt/github-gem#18]
I try to follow the tutorial :
http://github.com/guides/developing-with-submodules
after installing github-gem, updating gem, and adding json, when I type the command :

<pre>
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:1388:in `fu_list': undefined method `to_str' for nil:NilClass (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:1388:in `map'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:1388:in `fu_list'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:167:in `mkdir'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/lib/commands/commands.rb:187:in `command'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/bin/../lib/github/command.rb:25:in `send'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/bin/../lib/github/command.rb:25:in `call'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/bin/../lib/github.rb:76:in `invoke'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/bin/../lib/github.rb:70:in `activate'
    from /Library/Ruby/Gems/1.8/gems/github-0.4.1/bin/gh:8
    from /usr/bin/gh:19:in `load'
    from /usr/bin/gh:19
</pre>

**Comment by drnic** [comment]
I think I'm missing something after "when I type the command :". What command did you run here?

**Comment by drnic** [comment]
Closing because no additional info. Please recreate if its still an issue.
