### ISSUE TITLE
Issue email has wrong link

### ISSUE THREAD

**Issue by smathy** [defunkt/github-gem#2]
The issue email that is sent out when an issue is added to a repository that you're watching has the "Read more..." link as this (example from #1 of this repo): http://github.com//defunkt/github-gem/issues/1/find whereas it should be: http://github.com/defunkt/github-gem/issues/#issues/1

**Comment by smathy** [comment]
I erred.  It's not a notification email, it's my own private atom/rss feed.

**Comment by drnic** [comment]
Still a bug or can I close?

**Comment by smathy** [comment]
This can definitely be closed.  I think when I last commented was before they had added the ability for the opener to close an issue :)
