### ISSUE TITLE
create-from-local gives: "=> error creating repository"

### ISSUE THREAD

**Issue by Crazor** [defunkt/github-gem#24]
I just created a local git repository, added and committed a file and then issued "gh create-from-local", and the only output I get is "=> error creating repository".

This is not a very informative error message, and obviously the function does not work as expected (i.e. nothing happens, no github repo is created, and certainly no push is being done).

I'd be glad for some hints on how I resolve this problem.

**Comment by glennr** [comment]
+1 for this - also got this issue

**Comment by faradayio** [comment]
+1 me too

**Comment by ScottDugas** [comment]
I have created a fork of github-gem that resolves this issue for me.
It still has the cryptic message if something does go wrong, but it will create a public repository like it's supposed to (Before it would always try to create a private repository).

**Comment by ScottDugas** [comment]
Here is a link to the commit to fix this issue: http://github.com/snoopdugiedog/github-gem/commit/52836700c6ddf01191bc90f532fe418169ab2c86

**Comment by faradayio** [comment]
@snoopdugiedog awesome -- did you submit a pull request?

**Comment by Crazor** [comment]
I can confirm that the fix works and the issue is resolved. Thanks a lot!

**Comment by millisami** [comment]
Yup, this fix works. But why it hasn't been pulled in into the main repo??

**Comment by drnic** [comment]
Ok, pulled, thanks guys.
