### ISSUE TITLE
github network list fails with "redirection forbidden" on private repo

### ISSUE THREAD

**Issue by kocolosk** [defunkt/github-gem#4]
Traceback looks like

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:174:in `open_loop': redirection forbidden: http://github.com/user/repo/network/members.json -> https://github.com/user/repo/network/members.json (RuntimeError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:132:in`open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:518:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:30:in`open'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/lib/commands/helpers.rb:340:in `get_network_members'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/lib/commands/network.rb:23:in`command'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/bin/../lib/github/command.rb:25:in `send'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/bin/../lib/github/command.rb:25:in`call'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/bin/../lib/github.rb:74:in `invoke'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/bin/../lib/github.rb:68:in`activate'
    from /Library/Ruby/Gems/1.8/gems/defunkt-github-0.3.4/bin/github:8
    from /usr/bin/github:19:in `load'
    from /usr/bin/github:19

I didn't actually have an "origin" branch in this repo at first, so I added one that looks like

git remote show origin
- remote origin
  URL: git@github.com:user/repo.git
  HEAD branch: master
  ...

**Comment by fritzek** [comment]
same problem with github-gem 0.4.0

**Comment by jfturcot** [comment]
I am also having the exact same problem with 0.4.0

**Comment by chuckd** [comment]
same problem here. Tried modifying the URLs used to go straight to the https links, but then other things break...

**Comment by snowblink** [comment]
Does this work?
http://github.com/snowblink/github-gem/commit/3726b5e0f1f1129e41550f753e1d2207a3f5063c

**Comment by chuckd** [comment]
Yep this newer fix works. Much appreciated.

It's also a little nicer with a -s to curl to to remove the progress display.

**Comment by fritzek** [comment]
works for me too. thx @snowblink
thx, @chuckd, for the -s

**Comment by drnic** [comment]
Applied.
