### ISSUE TITLE
ruby1.8-dev dependency

### ISSUE THREAD

**Issue by nsp** [defunkt/github-gem#44]
It'd be nice if you removed the -dev dependency, or at least noted it in the readme. I'm not a ruby dev, but I figured out what the problem was after some googling revealed I needed 'mkmf' and it was in ruby1.8-dev (in the Ubuntu package manager, at least)

**Comment by drnic** [comment]
Hmm, its possible/likely that one of the following dependencies is a C-extension

<pre>
  s.add_dependency "text-hyphen", "1.0.0"
  s.add_dependency "text-format", "1.0.0"
  s.add_dependency "highline", "~> 1.5.1"
  s.add_dependency "json", "~> 1.4.6"
  s.add_dependency "launchy", "~> 0.3.7"
</pre>


It's interesting - I'm not sure how I would know as the author of this rubygem, if I'm using gems that have C-extensions. I guess I could install all the gems into a clean rvm gemset and see what looked like a C-extension. That's nasty.

I'll update the README based on your feedback.

**Comment by drnic** [comment]
Looks like its the json gem.

<pre>

$ rvm gemset create github-gem-test
'github-gem-test' gemset created (/Users/drnic/.rvm/gems/ruby-1.9.2-p180@github-gem-test).
$ rvm 1.9.2@github-gem-test
$ gem install github
Fetching: text-hyphen-1.0.0.gem (100%)
Fetching: text-format-1.0.0.gem (100%)
Fetching: highline-1.5.2.gem (100%)
Fetching: json-1.4.6.gem (100%)
Building native extensions.  This could take a while...
Fetching: configuration-1.2.0.gem (100%)
Fetching: launchy-0.3.7.gem (100%)
Fetching: github-0.6.1.gem (100%)
</pre>

**Comment by drnic** [comment]
I've reverted to only requiring json_pure now. Fixed by https://github.com/defunkt/github-gem/commit/01cdaffbfb8b733f08609f6dece8b05d70540a37

**Comment by nsp** [comment]
Excellent, thanks! I uninstalled ruby, rubydev-1.8 and github, and reinstalled no problem.
