### ISSUE TITLE
using it on an already cloned repository fails

### ISSUE THREAD

**Issue by digi604** [defunkt/github-gem#6]
$ github network
Error: remote 'origin' is not a github URL

origin url is:
Fetch URL: git+ssh://git@github.com/digi604/django-cms-2.0.git
Push  URL: git+ssh://git@github.com/digi604/django-cms-2.0.git

**Comment by drnic** [comment]
support git+ssh protocol for github.com remote urls. Closed by 81741358d0f8973ab02cb7773d36662823504b1d
