### ISSUE TITLE
win32-open3 not working with ruby 1.9.2

### ISSUE THREAD

**Issue by domainadmin** [defunkt/github-gem#77]
Although comes along with it, doesn't work.

Any alternatives...?

**Comment by ssboisen** [comment]
try https://github.com/matschaffer/win32-open3-19 which is available as a gem

**Comment by iki** [comment]
thanks @ssboisen, works ok after:

```
gem install win32-open3-19
```

@defunkt, or @kballard: can you update the message in https://github.com/defunkt/github-gem/blob/master/spec/windoze_spec.rb pls?
