### ISSUE TITLE
Create from local doesn't work

### ISSUE THREAD

**Issue by jgdavey** [defunkt/github-gem#9]
This applies to v0.4.0.

Although the command seems to work, the key ingredient (the curl command to actually create the repo on github) has a typo.

I've forked and fixed this, adding a slight bit more verbose output as well, following the pattern that Dr. Nic started in his recent enhancements.

**Comment by jgdavey** [comment]
Dr Nic recently released v0.4.1 to gemcutter, which fixes this bug.

**Comment by kch** [comment]
0.4.1 still has a bug that public is always being passed as false.

It's just lack of proper parenting (awful pun), which I did fix, but then I went ahead and refactored all `curl` calls to use a helper method instead.

All here on master: http://github.com/kch/github-gem

I have also made topic branches for each fix option, and another branch rebased on drnic's:
-   ### `create-from-local-snip-.git`
  
  Unrelated commit that handles the case where dir name has `.git` in it, remote would end in `.git.git`.
-   ### `create-from-local-public`
  
  Simple private/public in-place fix, includes previous.
-   ### `curl-refactor`
  
  Factor out all `curl` calls to a helper method, on top of previous.
-   ### `curl-refactor-on-drnic`
  
  Previous branch rebased on `drnic/master`.

**Comment by dolzenko** [comment]
Still not working for me:
    some_git_enabled_dir> github --debug create-from-local some_repo_name
    == Invoking `create-from-local`
    /usr/local/rvm/gems/ruby-1.9.2-head/gems/github-0.4.2/lib/github/command.rb:25:in `call': wrong number of arguments (1 for 0) (ArgumentError)

**Comment by drnic** [comment]
Merged in kch's branch; and using options[:private].nil? to determine "is public?"
